### ISSUE TITLE
Gallery doesn't work on python 3.11+

### ISSUE THREAD

**Issue by Codwizer** [hikariatama/Hikka#128]
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
The gallery and many other functions are not working because of the asyncio code update from python version 3.11+

**To Reproduce**
`AttributeError: module 'asyncio' has no attribute 'coroutine'`

**Expected behavior**
I expect Hikari to update to new versions of python

**Screenshots**
![IMG_20231221_225109_504.jpg](https://github.com/hikariatama/Hikka/assets/115508011/c76e6b76-aa56-411f-93dd-64c03b9a2526)

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux

- Hikka version: 1.6.3

**Comment by hikariatama** [comment]
Fixed in 1.6.4
